### ISSUE TITLE
No PickupPump on vehicle distance > RopeMaxLength

### ISSUE THREAD

**Issue by MrFrostDev** [Sna-aaa/qb-sna-fuel#2]
![image](https://user-images.githubusercontent.com/25389627/212540613-ddb14e43-7383-4299-876d-df450b15b2e8.png)
Just a small but important issue I've discovered. Currently testing out the best way to solve this.

**Comment by Sna-aaa** [comment]
Thanks a lot for the PR, it was the same solution as me :)
