### ISSUE TITLE
Error with qb-garages

### ISSUE THREAD

**Issue by pentafcb** [Sna-aaa/qb-sna-fuel#7]
![image](https://user-images.githubusercontent.com/68836355/214792825-c248b625-3460-4dfa-b411-637f4a573934.png)

**Comment by Sna-aaa** [comment]
You replaced the complete coding of my readme into qb-garage/client
In fact you just need to add one line
TriggerServerEvent('qb-fuel:server:UpdateVehicleDateTimeIn', plate)     --Change
Just before the line DeleteVehicle(veh, garage)
The better is to don't replace the other lines as the sample can be outdated or from another package

(here the line local totalFuel = GetFuel(veh) is not correct anymore for you with the standard qb-garages)
